#!/usr/bin/env python3
"""Generate wiki/watchlist.md (or wiki/watchlist.zh.md).

Scans each ticker directory for its most recent changelog entry and extracts
four fields: date, overall status, checked action (with detail), and next
review trigger. All four fields may span multiple lines (a markdown bullet or
``**Field**: ...`` block followed by indented continuation). This generator
collapses continuations into a single-line cell value for display.

Language modes:
- ``--lang en``: scan ``changelog.md`` with English field names.
- ``--lang zh``: scan ``changelog.zh.md`` when present (falling back to
  ``changelog.md``). Recognizes Chinese field names (``**总体**``,
  ``**下次审阅触发**``, double em-dash ``——``) and localizes column
  headers. Link paths in the ticker column still refer to the English
  overview by default — the watchlist is a cross-ticker summary, not a
  per-ticker page.
"""
import argparse
import re
import sys
from pathlib import Path

import frontmatter

# `## 2026-04-05 — Title` or `## [2026-04-05] — Title`. Accepts double em-dash too.
HEADING_RE = re.compile(
    r"^##\s*\[?(?P<date>\d{4}-\d{2}-\d{2})\]?\s*(?:——|—|-)\s*(?P<title>.+)$"
)

# - **Overall**: value   OR   - **总体**：value
STATUS_RE = re.compile(
    r"^\s*-\s*\*\*(?:Overall|总体)\*\*\s*[:：]\s*(?P<val>.+)$"
)

# - [x] rest-of-line
ACTION_LINE_RE = re.compile(r"^\s*-\s*\[x\]\s+(?P<rest>.+)$")

# **Next review trigger**: value   OR   **下次审阅触发**：value
NEXT_REVIEW_RE = re.compile(
    r"^\s*\*\*(?:Next review trigger|下次审阅触发|下次复核触发)\*\*\s*[:：]\s*(?P<val>.+)$"
)

# Max characters for a single cell (keeps tables from becoming unreadable).
CELL_MAX_LEN = 120

LANG_STRINGS = {
    "en": {
        "title": "# Watchlist — Cross-Ticker Ranking",
        "auto_note": "*Auto-generated by `scripts/gen_watchlist.py`. Do not edit by hand.*",
        "table_header": "| Ticker | Source | Latest | Status | Action | Next Review |",
        "table_divider": "|--------|--------|--------|--------|--------|-------------|",
        "no_changelog": "_(no changelog)_",
    },
    "zh": {
        "title": "# 观察列表 —— 跨股票排序",
        "auto_note": "*由 `scripts/gen_watchlist.py` 自动生成。请勿手动编辑。*",
        "table_header": "| Ticker | 来源 | 最新 | 状态 | 操作 | 下次复核 |",
        "table_divider": "|--------|------|------|------|------|----------|",
        "no_changelog": "_（无变更日志）_",
    },
}

# Continuation-line detection: stop when we hit a sibling bullet, new
# field heading, new section (###/##), or a fresh blank paragraph break.
def _is_continuation(line: str) -> bool:
    if not line.strip():
        return False
    stripped = line.lstrip()
    if stripped.startswith(("- ", "* ", "+ ")):
        return False
    if stripped.startswith("#"):
        return False
    if stripped.startswith(("**",)) and (":" in stripped or "：" in stripped):
        # Likely a new **Field**: block; stop consuming.
        return False
    if stripped.startswith("---"):
        return False
    # Indented line (leading whitespace) or plain prose — treat as continuation.
    return bool(re.match(r"^\s{2,}\S", line)) or not line.startswith(("#", "-"))


def _consume_continuations(lines: list[str], start: int, seed: str) -> str:
    """Starting from index `start + 1`, greedily append continuation lines."""
    accum = seed
    j = start + 1
    while j < len(lines):
        if not _is_continuation(lines[j]):
            break
        accum += " " + lines[j].strip()
        j += 1
    return accum


def _strip_bold(s: str) -> str:
    return re.sub(r"\*\*(.+?)\*\*", r"\1", s).strip()


def _split_action(rest: str) -> tuple[str, str]:
    """Split action-and-detail on em-dash (single or double)."""
    for sep in (" —— ", "——", " — ", "—"):
        if sep in rest:
            action, _, detail = rest.partition(sep)
            return _strip_bold(action), detail.strip()
    return _strip_bold(rest), ""


def _sanitize_cell(text: str, max_len: int = CELL_MAX_LEN) -> str:
    """Prepare a value for a markdown table cell."""
    # Collapse internal whitespace.
    text = re.sub(r"\s+", " ", text).strip()
    # Pipe chars would break the table row.
    text = text.replace("|", "/")
    if len(text) > max_len:
        # Prefer space boundary for English; hard cut for Chinese.
        truncated = text[: max_len]
        if " " in truncated[-30:]:
            truncated = truncated.rsplit(" ", 1)[0]
        text = truncated + "…"
    return text


def parse_latest_entry(changelog_path: Path):
    if not changelog_path.is_file():
        return None
    text = changelog_path.read_text(encoding="utf-8")
    lines = text.splitlines()

    latest = None
    for i, line in enumerate(lines):
        m = HEADING_RE.match(line)
        if m:
            latest = {
                "date": m.group("date"),
                "title": m.group("title"),
                "start": i,
                "status": "",
                "action": "",
                "next_review": "",
            }
            break
    if not latest:
        return None

    # Find the next-entry boundary so we don't leak into older entries.
    entry_end = len(lines)
    for i in range(latest["start"] + 1, len(lines)):
        if lines[i].startswith("## "):
            entry_end = i
            break

    i = latest["start"] + 1
    while i < entry_end:
        line = lines[i]

        m = STATUS_RE.match(line)
        if m and not latest["status"]:
            value = _consume_continuations(lines, i, m.group("val").strip())
            latest["status"] = _sanitize_cell(value)

        m = ACTION_LINE_RE.match(line)
        if m and not latest["action"]:
            rest = _consume_continuations(lines, i, m.group("rest").strip())
            action, detail = _split_action(rest)
            composed = f"{action} — {detail}" if detail else action
            latest["action"] = _sanitize_cell(composed)

        m = NEXT_REVIEW_RE.match(line)
        if m and not latest["next_review"]:
            value = _consume_continuations(lines, i, m.group("val").strip())
            latest["next_review"] = _sanitize_cell(value)

        i += 1

    return latest


def pick_changelog(ticker_dir: Path, lang: str) -> Path:
    """In zh mode, prefer changelog.zh.md when present."""
    if lang == "zh":
        zh = ticker_dir / "changelog.zh.md"
        if zh.is_file():
            return zh
    return ticker_dir / "changelog.md"


def collect(wiki_root: Path, lang: str):
    rows = []
    tickers_dir = wiki_root / "tickers"
    if not tickers_dir.is_dir():
        return rows
    strings = LANG_STRINGS[lang]
    for ticker_dir in sorted(tickers_dir.iterdir()):
        overview = ticker_dir / "overview.md"
        if not overview.is_file():
            continue
        post = frontmatter.loads(overview.read_text(encoding="utf-8"))
        entry = parse_latest_entry(pick_changelog(ticker_dir, lang))
        rows.append({
            "ticker": post.get("ticker", ticker_dir.name),
            "source": post.get("source", ""),
            "date": entry["date"] if entry else "",
            "status": entry["status"] if entry and entry["status"] else strings["no_changelog"],
            "action": entry["action"] if entry and entry["action"] else strings["no_changelog"],
            "next_review": entry["next_review"] if entry else "",
        })
    return rows


def render(rows, strings):
    lines = [
        strings["title"] + "\n",
        strings["auto_note"] + "\n",
        strings["table_header"],
        strings["table_divider"],
    ]
    for r in rows:
        lines.append(
            f"| {r['ticker']} | {r['source']} | {r['date']} | {r['status']} | {r['action']} | {r['next_review']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wiki-root", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--lang", choices=["en", "zh"], default="en")
    args = ap.parse_args()
    strings = LANG_STRINGS[args.lang]
    rows = collect(args.wiki_root, args.lang)
    args.output.write_text(render(rows, strings), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
