#!/usr/bin/env python3
"""Generate wiki/watchlist.md by scanning each ticker's latest changelog entry."""
import argparse
import re
import sys
from pathlib import Path

import frontmatter

HEADING_RE = re.compile(r"^##\s*\[(?P<date>\d{4}-\d{2}-\d{2})\]\s*—\s*(?P<title>.+)$")
THESIS_STATUS_RE = re.compile(r"^\s*-\s*\*\*Overall\*\*:\s*(?P<status>.+)$")
CHECKED_ACTION_RE = re.compile(r"^\s*-\s*\[x\]\s*(?P<action>[^—\-\n]+?)(?:\s*—\s*(?P<detail>.+))?$")
NEXT_REVIEW_RE = re.compile(r"^\s*\*\*Next review trigger\*\*:\s*(?P<trigger>.+)$")


def parse_latest_entry(changelog_path: Path):
    if not changelog_path.is_file():
        return None
    text = changelog_path.read_text(encoding="utf-8")
    lines = text.splitlines()
    latest = None
    for i, line in enumerate(lines):
        m = HEADING_RE.match(line)
        if m:
            latest = {"date": m.group("date"), "title": m.group("title"),
                      "start": i, "status": "", "action": "", "next_review": ""}
            break
    if not latest:
        return None
    j = latest["start"] + 1
    while j < len(lines) and not lines[j].startswith("## "):
        line = lines[j]
        m = THESIS_STATUS_RE.match(line)
        if m and not latest["status"]:
            latest["status"] = m.group("status").strip()
        m = CHECKED_ACTION_RE.match(line)
        if m and not latest["action"]:
            action = m.group("action").strip()
            detail = (m.group("detail") or "").strip()
            latest["action"] = f"{action} — {detail}" if detail else action
        m = NEXT_REVIEW_RE.match(line)
        if m and not latest["next_review"]:
            latest["next_review"] = m.group("trigger").strip()
        j += 1
    return latest


def collect(wiki_root: Path):
    rows = []
    tickers_dir = wiki_root / "tickers"
    if not tickers_dir.is_dir():
        return rows
    for ticker_dir in sorted(tickers_dir.iterdir()):
        overview = ticker_dir / "overview.md"
        if not overview.is_file():
            continue
        post = frontmatter.loads(overview.read_text(encoding="utf-8"))
        entry = parse_latest_entry(ticker_dir / "changelog.md")
        rows.append({
            "ticker": post.get("ticker", ticker_dir.name),
            "source": post.get("source", ""),
            "date": entry["date"] if entry else "",
            "status": entry["status"] if entry else "_(no changelog)_",
            "action": entry["action"] if entry else "_(no changelog)_",
            "next_review": entry["next_review"] if entry else "",
        })
    return rows


def render(rows):
    lines = [
        "# Watchlist — Cross-Ticker Ranking\n",
        "*Auto-generated by `scripts/gen_watchlist.py`. Do not edit by hand.*\n",
        "| Ticker | Source | Latest | Status | Action | Next Review |",
        "|--------|--------|--------|--------|--------|-------------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['ticker']} | {r['source']} | {r['date']} | {r['status']} | {r['action']} | {r['next_review']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wiki-root", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    args = ap.parse_args()
    rows = collect(args.wiki_root)
    args.output.write_text(render(rows), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
