#!/usr/bin/env python3
"""Generate wiki/index.md (or wiki/index.zh.md) by scanning tickers/*/overview.md.

Two modes:

1. **Upstream-base mode** (``--upstream-index`` provided):
   Copies the upstream index.md verbatim and appends an
   "Austin's Overlay Tickers" section at the bottom. Only overlay tickers
   (source == "austin") are appended; upstream tickers are already in the
   upstream index.

2. **Standalone mode** (no ``--upstream-index``):
   Generates the index from scratch, grouping tickers by source.

Language modes:
- ``--lang en`` (default): scan ``overview.md`` only. Index links point to
  ``overview.md``.
- ``--lang zh``: scan ``overview.zh.md`` when present, falling back to
  ``overview.md`` when the ticker lacks a Chinese variant. Index links point
  to whichever file provided the summary. Headings and column labels are
  localized.
"""
import argparse
import re
import sys
from pathlib import Path

import frontmatter

LAST_UPDATED_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*Last [Uu]pdated?\*\*:\s*(?P<date>\d{4}-\d{2}-\d{2})",
    re.MULTILINE,
)

# Chinese variant: `**最后更新**: YYYY-MM-DD` or similar.
LAST_UPDATED_ZH_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*(?:最后更新|最近更新|更新时间|更新日期)\*\*[:：]\s*(?P<date>\d{4}-\d{2}-\d{2})",
    re.MULTILINE,
)

CHANGELOG_HEADING_RE = re.compile(
    r"^##\s*\[?(?P<date>\d{4}-\d{2}-\d{2})\]?\s*[—\-]",
    re.MULTILINE,
)

# Overlay overview.md patterns.
# "# POET — POET Technologies" but NOT "# POET — Overview" / "# EBAY — 概览"
H1_COMPANY_RE = re.compile(r"^#\s+\S+\s+[—\-]+\s+(?!(?:Overview|概览)\s*$)(.+)$", re.MULTILINE)
# "**Status**: ..." bare style or "> **Status**: ..." blockquote style
STATUS_FIELD_RE = re.compile(r"^\s*(?:>\s*)?\*\*Status\*\*:\s*(.+)$", re.MULTILINE)
# "> **Moat**: Narrow" blockquote style (used by EBAY-style files)
MOAT_INLINE_RE = re.compile(r"^\s*(?:>\s*)?\*\*Moat\*\*:\s*(.+)$", re.MULTILINE)
# Section "## Business in One Line" followed by blank lines then content.
BIZ_ONE_LINE_RE = re.compile(
    r"##\s+Business in One Line\s*\n+(.+?)(?=\n---|\n##|\Z)", re.DOTALL
)
# "## Business Description" as fallback (used by EBAY-style files)
BIZ_DESC_RE = re.compile(
    r"##\s+Business Description\s*\n+(.+?)(?=\n---|\n##|\Z)", re.DOTALL
)
# Under "## Moat", look for "### Verdict\n\n**...**" or inline "Verdict: **...**"
MOAT_VERDICT_RE = re.compile(
    r"##\s+Moat.*?(?:###\s+Verdict\s*\n+\*\*(.+?)\*\*|(?:^|\n)Verdict:\s*\*\*(.+?)\*\*)",
    re.DOTALL,
)

# ── Chinese overlay patterns ──────────────────────────────────────────────────
# "**状态**: ..." bare or "> **状态**：..." blockquote, half/full-width colon
STATUS_ZH_RE = re.compile(r"^\s*(?:>\s*)?\*\*状态\*\*[:：]\s*(.+)$", re.MULTILINE)
# "> **护城河**：窄" inline blockquote (EBAY zh style)
MOAT_INLINE_ZH_RE = re.compile(r"^\s*(?:>\s*)?\*\*护城河\*\*[:：]\s*(.+)$", re.MULTILINE)
# "## 一句话业务描述"
BIZ_ONE_LINE_ZH_RE = re.compile(
    r"##\s+一句话业务描述\s*\n+(.+?)(?=\n---|\n##|\Z)", re.DOTALL
)
# Under "## 护城河": "### 结论\n\n**...**" heading style OR inline "结论: **...**"
MOAT_VERDICT_ZH_RE = re.compile(
    r"##\s+护城河.*?(?:###\s+结论\s*\n+\*\*(.+?)\*\*|(?:^|\n)结论[:：]\s*\*\*(.+?)\*\*)",
    re.DOTALL,
)
# Company name from body: "eBay Inc. is a global..." — allow dots, skip common sentence starters
COMPANY_FROM_BODY_RE = re.compile(
    r"^((?!(?:Its|The|This|It|A|An|Note|See|Per|At|By|In|On)\s)[A-Za-z][^\n]{2,60}?) (?:is |was |operates )",
    re.MULTILINE,
)

SUMMARY_MAX_LEN_EN = 160
SUMMARY_MAX_LEN_ZH = 80
SUMMARY_MIN_LEN_EN = 40
SUMMARY_MIN_LEN_ZH = 15

_NON_PROSE_PREFIXES = (">", "**", "#", "---", "- ", "* ", "|", "`")

LANG_STRINGS = {
    "en": {
        "title": "# Ticker Index",
        "auto_note": "*Auto-generated by `scripts/gen_index.py`. Do not edit by hand.*",
        "upstream_heading": "## Upstream Tickers",
        "austin_heading": "## My Tickers",
        "overlay_heading": "## Austin's Overlay Tickers",
        "overlay_note": "*Tickers researched independently in `rwh-overlay`. Not part of upstream coverage.*",
        "overlay_table_header": "| Ticker | Status | Company | Moat | Last Updated | Summary |",
        "overlay_table_divider": "|--------|--------|---------|------|--------------|---------|",
        "table_header": "| Ticker | Summary | Updated |",
        "table_divider": "|--------|---------|---------|",
        "empty": "_(none)_\n",
    },
    "zh": {
        "title": "# 股票索引",
        "auto_note": "*由 `scripts/gen_index.py` 自动生成。请勿手动编辑。*",
        "upstream_heading": "## 上游股票（kgajjala）",
        "austin_heading": "## 我的股票",
        "overlay_heading": "## Austin 的 Overlay 股票",
        "overlay_note": "*在 `rwh-overlay` 独立研究的股票，不属于上游覆盖范围。*",
        "overlay_table_header": "| Ticker | 状态 | 公司 | 护城河 | 最后更新 | 摘要 |",
        "overlay_table_divider": "|--------|------|------|--------|----------|------|",
        "table_header": "| Ticker | 摘要 | 更新于 |",
        "table_divider": "|--------|------|--------|",
        "empty": "_（无）_\n",
    },
}


def extract_last_updated(body: str, lang: str = "en") -> str:
    m = LAST_UPDATED_RE.search(body)
    if m:
        return m.group("date")
    if lang == "zh":
        m = LAST_UPDATED_ZH_RE.search(body)
        if m:
            return m.group("date")
    return ""


def extract_date_from_changelog(changelog_path: Path) -> str:
    if not changelog_path.is_file():
        return ""
    m = CHANGELOG_HEADING_RE.search(changelog_path.read_text(encoding="utf-8"))
    return m.group("date") if m else ""


def extract_summary(body: str, max_len: int, min_len: int) -> str:
    for paragraph in body.split("\n\n"):
        lines = [l.strip() for l in paragraph.splitlines() if l.strip()]
        if not lines:
            continue
        if all(l.startswith(_NON_PROSE_PREFIXES) for l in lines):
            continue
        text = " ".join(lines)
        text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
        text = re.sub(r"\*(.+?)\*", r"\1", text)
        text = text.replace("|", "/")
        if len(text) < min_len:
            continue
        if len(text) > max_len:
            truncated = text[:max_len]
            if " " in truncated[-30:]:
                truncated = truncated.rsplit(" ", 1)[0]
            return truncated + "…"
        return text
    return ""


def _sanitize_cell(text: str, max_len: int = 100) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = text.replace("|", "/")
    if len(text) > max_len:
        truncated = text[:max_len]
        if " " in truncated[-20:]:
            truncated = truncated.rsplit(" ", 1)[0]
        text = truncated + "…"
    return text


def extract_overlay_fields(body: str, lang: str = "en") -> dict:
    """Extract Status, Company, Moat verdict, and summary from overlay overview.md.

    Handles EN formats (bare/blockquote) and ZH format (Chinese field names).
    """
    # Company: from H1 title if it contains a real name (not just "Overview")
    company = ""
    m = H1_COMPANY_RE.search(body)
    if m:
        company = m.group(1).strip()
    if not company:
        m = COMPANY_FROM_BODY_RE.search(body)
        if m:
            company = m.group(1).strip()

    if lang == "zh":
        # Company fallback: "eBay Inc. 是一家..." (zh body uses 是/为)
        if not company:
            m = re.search(
                r"^((?!(?:其|这|该|此|以下)\s)[A-Za-z一-鿿][^\n]{2,50}?)\s+(?:是一家|是一个|是全球|是美国|为)",
                body, re.MULTILINE,
            )
            if m:
                company = m.group(1).strip()

        # Status: bare or blockquote, half/full-width colon
        status = ""
        m = STATUS_ZH_RE.search(body)
        if m:
            raw = m.group(1).strip()
            # Strip bold markers inside parentheses, tier annotations
            raw = re.sub(r"\*\*(.+?)\*\*", r"\1", raw)
            raw = re.sub(r"[（(][^）)]*[）)]", "", raw).strip()
            raw = re.sub(r"\s*[—\-]+\s*(?:初始论文|编制于|compiled|updated)[^\n]*$", "", raw).strip()
            status = _sanitize_cell(raw, max_len=60)

        # Moat: inline blockquote (EBAY zh style) first, then verdict under ## 护城河
        moat = ""
        m = MOAT_INLINE_ZH_RE.search(body)
        if m:
            moat = _sanitize_cell(m.group(1).strip(), max_len=60)
        if not moat:
            m = MOAT_VERDICT_ZH_RE.search(body)
            if m:
                moat = _sanitize_cell((m.group(1) or m.group(2) or "").strip(), max_len=60)

        # Summary: zh "## 一句话业务描述"
        summary = ""
        m = BIZ_ONE_LINE_ZH_RE.search(body)
        if m:
            raw_biz = m.group(1).strip()
            lines = [l.strip() for l in raw_biz.splitlines() if l.strip()]
            candidate = _sanitize_cell(" ".join(lines), max_len=120)
            if len(candidate) >= SUMMARY_MIN_LEN_ZH:
                summary = candidate
    else:
        # Status: bare or blockquote EN format
        status = ""
        m = STATUS_FIELD_RE.search(body)
        if m:
            raw = m.group(1).strip()
            raw = re.sub(r"\(SPECULATIVE(?:\s*/[^)]+)?\s*tier\)", "Speculative", raw, flags=re.IGNORECASE)
            raw = re.sub(r"\(SPECULATIVE[^)]*\)", "Speculative", raw, flags=re.IGNORECASE)
            raw = re.sub(r"\s*[—\-]+\s*(?:compiled|updated)\s+\d{4}-\d{2}-\d{2}\s*$", "", raw, flags=re.IGNORECASE)
            status = _sanitize_cell(raw, max_len=60)

        # Moat: inline blockquote first, then Verdict under ## Moat
        moat = ""
        m = MOAT_INLINE_RE.search(body)
        if m:
            moat = _sanitize_cell(m.group(1).strip(), max_len=60)
        if not moat:
            m = MOAT_VERDICT_RE.search(body)
            if m:
                moat = _sanitize_cell((m.group(1) or m.group(2) or "").strip(), max_len=60)

        # Summary: "Business in One Line" → "Business Description"
        summary = ""
        for pattern in (BIZ_ONE_LINE_RE, BIZ_DESC_RE):
            m = pattern.search(body)
            if m:
                raw_biz = m.group(1).strip()
                lines = [l.strip() for l in raw_biz.splitlines() if l.strip()]
                candidate = _sanitize_cell(" ".join(lines), max_len=160)
                if len(candidate) >= SUMMARY_MIN_LEN_EN:
                    summary = candidate
                    break

    return {"company": company, "status": status, "moat": moat, "summary": summary}


def pick_overview(ticker_dir: Path, lang: str) -> tuple[Path, str]:
    """Return (chosen_overview_path, link_filename) for the given language.

    Falls back to {TICKER}.md for upstream tickers that don't use overview.md.
    """
    en = ticker_dir / "overview.md"
    zh = ticker_dir / "overview.zh.md"
    if lang == "zh" and zh.is_file():
        return zh, "overview.zh.md"
    if en.is_file():
        return en, "overview.md"
    ticker_md = ticker_dir / f"{ticker_dir.name}.md"
    return ticker_md, f"{ticker_dir.name}.md"


def pick_changelog(ticker_dir: Path, lang: str) -> Path:
    if lang == "zh":
        zh = ticker_dir / "changelog.zh.md"
        if zh.is_file():
            return zh
    return ticker_dir / "changelog.md"


def collect(wiki_root: Path, lang: str):
    rows = {"upstream": [], "austin": []}
    tickers_dir = wiki_root / "tickers"
    if not tickers_dir.is_dir():
        return rows
    max_len = SUMMARY_MAX_LEN_ZH if lang == "zh" else SUMMARY_MAX_LEN_EN
    min_len = SUMMARY_MIN_LEN_ZH if lang == "zh" else SUMMARY_MIN_LEN_EN
    for ticker_dir in sorted(tickers_dir.iterdir()):
        overview, link_name = pick_overview(ticker_dir, lang)
        if not overview.is_file():
            continue
        post = frontmatter.loads(overview.read_text(encoding="utf-8"))
        src = post.get("source")
        if not src:
            en_post = frontmatter.loads((ticker_dir / "overview.md").read_text(encoding="utf-8"))
            src = en_post.get("source", "unknown")
        if src not in rows:
            continue
        summary = post.get("summary") or extract_summary(post.content, max_len, min_len)
        updated = (
            post.get("updated")
            or extract_last_updated(post.content, lang)
            or extract_date_from_changelog(pick_changelog(ticker_dir, lang))
        )
        rows[src].append({
            "ticker": post.get("ticker", ticker_dir.name),
            "summary": summary,
            "updated": updated,
            "path": f"tickers/{ticker_dir.name}/{link_name}",
        })
    return rows


def collect_overlay(wiki_root: Path, lang: str) -> list[dict]:
    """Collect only austin-sourced tickers with enriched overlay fields."""
    tickers_dir = wiki_root / "tickers"
    if not tickers_dir.is_dir():
        return []
    rows = []
    for ticker_dir in sorted(tickers_dir.iterdir()):
        overview_en = ticker_dir / "overview.md"
        if not overview_en.is_file():
            continue
        post_en = frontmatter.loads(overview_en.read_text(encoding="utf-8"))
        if post_en.get("source") != "austin":
            continue

        if lang == "zh":
            zh_path = ticker_dir / "overview.zh.md"
            overview_path, link_name = (zh_path, "overview.zh.md") if zh_path.is_file() else (overview_en, "overview.md")
        else:
            overview_path, link_name = overview_en, "overview.md"

        post = frontmatter.loads(overview_path.read_text(encoding="utf-8"))
        fields = extract_overlay_fields(post.content, lang)
        updated = (
            post.get("updated")
            or extract_last_updated(post.content, lang)
            or extract_date_from_changelog(pick_changelog(ticker_dir, lang))
        )
        rows.append({
            "ticker": post_en.get("ticker", ticker_dir.name),
            "path": f"tickers/{ticker_dir.name}/{link_name}",
            "status": fields["status"],
            "company": fields["company"],
            "moat": fields["moat"],
            "updated": updated,
            "summary": fields["summary"],
        })
    return rows


def render_table(rows, strings):
    if not rows:
        return strings["empty"]
    lines = [strings["table_header"], strings["table_divider"]]
    for r in rows:
        lines.append(f"| [{r['ticker']}]({r['path']}) | {r['summary']} | {r['updated']} |")
    return "\n".join(lines) + "\n"


def render_overlay_table(rows: list[dict], strings: dict) -> str:
    if not rows:
        return strings["empty"]
    lines = [strings["overlay_table_header"], strings["overlay_table_divider"]]
    for r in rows:
        lines.append(
            f"| [{r['ticker']}]({r['path']}) | {r['status']} | {r['company']} "
            f"| {r['moat']} | {r['updated']} | {r['summary']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wiki-root", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--lang", choices=["en", "zh"], default="en",
                    help="Language mode. zh prefers overview.zh.md, localizes labels.")
    ap.add_argument("--upstream-index", type=Path, default=None,
                    help="Path to upstream index.md. When provided, its content is used "
                         "verbatim as the base and overlay tickers are appended at the end.")
    args = ap.parse_args()

    strings = LANG_STRINGS[args.lang]

    if args.upstream_index and args.upstream_index.is_file():
        upstream_content = args.upstream_index.read_text(encoding="utf-8").rstrip()
        overlay_rows = collect_overlay(args.wiki_root, args.lang)
        parts = [
            upstream_content,
            "",
            "---",
            "",
            strings["overlay_heading"],
            "",
            strings["overlay_note"],
            "",
            render_overlay_table(overlay_rows, strings),
        ]
        args.output.write_text("\n".join(parts), encoding="utf-8")
    else:
        rows = collect(args.wiki_root, args.lang)
        out = [
            strings["title"] + "\n",
            strings["auto_note"] + "\n",
            strings["upstream_heading"] + "\n",
            render_table(rows["upstream"], strings),
            strings["austin_heading"] + "\n",
            render_table(rows["austin"], strings),
        ]
        args.output.write_text("\n".join(out), encoding="utf-8")

    return 0


if __name__ == "__main__":
    sys.exit(main())
