#!/usr/bin/env python3
"""Generate wiki/index.md (or wiki/index.zh.md) by scanning tickers/*/overview.md.

Reads `summary` and `updated` from frontmatter when present; otherwise falls
back to extracting them from the body. Upstream (kgajjala) tickers use the
blockquote style (``> **Last Updated**: YYYY-MM-DD``); overlay tickers use
the bare style (``**Last updated**: YYYY-MM-DD``). Both are recognized.

Language modes:
- ``--lang en`` (default): scan ``overview.md`` only. Index links point to
  ``overview.md``.
- ``--lang zh``: scan ``overview.zh.md`` when present, falling back to
  ``overview.md`` when the ticker lacks a Chinese variant. Index links point
  to whichever file provided the summary. Headings and column labels are
  localized.
"""
import argparse
import re
import sys
from pathlib import Path

import frontmatter

LAST_UPDATED_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*Last [Uu]pdated?\*\*:\s*(?P<date>\d{4}-\d{2}-\d{2})",
    re.MULTILINE,
)

# Chinese variant: `**最后更新**: YYYY-MM-DD` or similar.
LAST_UPDATED_ZH_RE = re.compile(
    r"^\s*(?:>\s*)?\*\*(?:最后更新|最近更新|更新时间|更新日期)\*\*[:：]\s*(?P<date>\d{4}-\d{2}-\d{2})",
    re.MULTILINE,
)

CHANGELOG_HEADING_RE = re.compile(
    r"^##\s*\[?(?P<date>\d{4}-\d{2}-\d{2})\]?\s*[—\-]",
    re.MULTILINE,
)

SUMMARY_MAX_LEN_EN = 160
SUMMARY_MAX_LEN_ZH = 80  # Chinese characters are ~2x information density; shorter limit.
SUMMARY_MIN_LEN_EN = 40
SUMMARY_MIN_LEN_ZH = 15  # Chinese characters pack more info per char; shorter minimum.

# Paragraphs whose every non-empty line starts with any of these prefixes are
# considered metadata/structure, not prose.
_NON_PROSE_PREFIXES = (">", "**", "#", "---", "- ", "* ", "|", "`")

LANG_STRINGS = {
    "en": {
        "title": "# Ticker Index",
        "auto_note": "*Auto-generated by `scripts/gen_index.py`. Do not edit by hand.*",
        "upstream_heading": "## Upstream Tickers",
        "austin_heading": "## My Tickers",
        "table_header": "| Ticker | Summary | Updated |",
        "table_divider": "|--------|---------|---------|",
        "empty": "_(none)_\n",
    },
    "zh": {
        "title": "# 股票索引",
        "auto_note": "*由 `scripts/gen_index.py` 自动生成。请勿手动编辑。*",
        "upstream_heading": "## 上游股票（kgajjala）",
        "austin_heading": "## 我的股票",
        "table_header": "| Ticker | 摘要 | 更新于 |",
        "table_divider": "|--------|------|--------|",
        "empty": "_（无）_\n",
    },
}


def extract_last_updated(body: str, lang: str = "en") -> str:
    # Try English variant first (most common), then Chinese variant.
    m = LAST_UPDATED_RE.search(body)
    if m:
        return m.group("date")
    if lang == "zh":
        m = LAST_UPDATED_ZH_RE.search(body)
        if m:
            return m.group("date")
    return ""


def extract_date_from_changelog(changelog_path: Path) -> str:
    """Return the date of the first (most recent) ``## DATE —`` heading, or ''."""
    if not changelog_path.is_file():
        return ""
    m = CHANGELOG_HEADING_RE.search(changelog_path.read_text(encoding="utf-8"))
    return m.group("date") if m else ""


def extract_summary(body: str, max_len: int, min_len: int) -> str:
    """Return the first substantive prose paragraph, squashed and truncated."""
    for paragraph in body.split("\n\n"):
        lines = [l.strip() for l in paragraph.splitlines() if l.strip()]
        if not lines:
            continue
        if all(l.startswith(_NON_PROSE_PREFIXES) for l in lines):
            continue
        text = " ".join(lines)
        # Strip bold/italic markers for cleaner table display.
        text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
        text = re.sub(r"\*(.+?)\*", r"\1", text)
        # Collapse pipe characters (would break the markdown table row).
        text = text.replace("|", "/")
        if len(text) < min_len:
            continue
        if len(text) > max_len:
            # For Chinese, no word boundaries — just hard truncate and append ellipsis.
            # For English, try to break on a space.
            truncated = text[: max_len]
            if " " in truncated[-30:]:
                truncated = truncated.rsplit(" ", 1)[0]
            return truncated + "…"
        return text
    return ""


def pick_overview(ticker_dir: Path, lang: str) -> tuple[Path, str]:
    """Return (chosen_overview_path, link_filename) for the given language.

    In zh mode: prefer overview.zh.md if present, else fall back to overview.md.
    In en mode: always overview.md (ignore .zh.md).
    """
    en = ticker_dir / "overview.md"
    zh = ticker_dir / "overview.zh.md"
    if lang == "zh" and zh.is_file():
        return zh, "overview.zh.md"
    return en, "overview.md"


def pick_changelog(ticker_dir: Path, lang: str) -> Path:
    """Return the appropriate changelog path for the given language."""
    if lang == "zh":
        zh = ticker_dir / "changelog.zh.md"
        if zh.is_file():
            return zh
    return ticker_dir / "changelog.md"


def collect(wiki_root: Path, lang: str):
    rows = {"upstream": [], "austin": []}
    tickers_dir = wiki_root / "tickers"
    if not tickers_dir.is_dir():
        return rows
    max_len = SUMMARY_MAX_LEN_ZH if lang == "zh" else SUMMARY_MAX_LEN_EN
    min_len = SUMMARY_MIN_LEN_ZH if lang == "zh" else SUMMARY_MIN_LEN_EN
    for ticker_dir in sorted(tickers_dir.iterdir()):
        overview, link_name = pick_overview(ticker_dir, lang)
        if not overview.is_file():
            continue
        post = frontmatter.loads(overview.read_text(encoding="utf-8"))
        # Source is tagged on overview.md; overview.zh.md may not have
        # source tagged because inject_frontmatter runs once per file. Fall
        # back to overview.md frontmatter for the source field.
        src = post.get("source")
        if not src:
            en_post = frontmatter.loads((ticker_dir / "overview.md").read_text(encoding="utf-8"))
            src = en_post.get("source", "unknown")
        if src not in rows:
            continue
        summary = post.get("summary") or extract_summary(post.content, max_len, min_len)
        updated = (
            post.get("updated")
            or extract_last_updated(post.content, lang)
            or extract_date_from_changelog(pick_changelog(ticker_dir, lang))
        )
        rows[src].append({
            "ticker": post.get("ticker", ticker_dir.name),
            "summary": summary,
            "updated": updated,
            "path": f"tickers/{ticker_dir.name}/{link_name}",
        })
    return rows


def render_table(rows, strings):
    if not rows:
        return strings["empty"]
    lines = [strings["table_header"], strings["table_divider"]]
    for r in rows:
        lines.append(f"| [{r['ticker']}]({r['path']}) | {r['summary']} | {r['updated']} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wiki-root", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--lang", choices=["en", "zh"], default="en",
                    help="Language mode. zh prefers overview.zh.md, localizes labels.")
    args = ap.parse_args()

    strings = LANG_STRINGS[args.lang]
    rows = collect(args.wiki_root, args.lang)

    out = [
        strings["title"] + "\n",
        strings["auto_note"] + "\n",
        strings["upstream_heading"] + "\n",
        render_table(rows["upstream"], strings),
        strings["austin_heading"] + "\n",
        render_table(rows["austin"], strings),
    ]
    args.output.write_text("\n".join(out), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
