#!/usr/bin/env python3
"""Generate wiki/index.md by scanning tickers/*/overview.md frontmatter."""
import argparse
import sys
from pathlib import Path

import frontmatter


def collect(wiki_root: Path):
    rows = {"upstream": [], "austin": []}
    tickers_dir = wiki_root / "tickers"
    if not tickers_dir.is_dir():
        return rows
    for ticker_dir in sorted(tickers_dir.iterdir()):
        overview = ticker_dir / "overview.md"
        if not overview.is_file():
            continue
        post = frontmatter.loads(overview.read_text(encoding="utf-8"))
        src = post.get("source", "unknown")
        if src not in rows:
            continue
        rows[src].append({
            "ticker": post.get("ticker", ticker_dir.name),
            "summary": post.get("summary", ""),
            "updated": post.get("updated", ""),
            "path": f"tickers/{ticker_dir.name}/overview.md",
        })
    return rows


def render_table(rows):
    if not rows:
        return "_(none)_\n"
    lines = [
        "| Ticker | Summary | Updated |",
        "|--------|---------|---------|",
    ]
    for r in rows:
        lines.append(f"| [{r['ticker']}]({r['path']}) | {r['summary']} | {r['updated']} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wiki-root", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    args = ap.parse_args()

    rows = collect(args.wiki_root)

    out = []
    out.append("# Ticker Index\n")
    out.append("*Auto-generated by `scripts/gen_index.py`. Do not edit by hand.*\n")
    out.append("## Upstream Tickers\n")
    out.append(render_table(rows["upstream"]))
    out.append("## My Tickers\n")
    out.append(render_table(rows["austin"]))
    args.output.write_text("\n".join(out), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
