#!/usr/bin/env python3
"""Merge upstream log.md and overlay overlay-log.md into a single fenced log.

Extracts lines matching `LOG YYYY-MM-DD HH:MM ...` from both inputs,
sorts by timestamp, and wraps the result in a single fenced code block
to preserve per-line rendering (per CLAUDE.md).
"""
import argparse
import re
import sys
from pathlib import Path

LOG_LINE_RE = re.compile(r"^LOG\s+(?P<ts>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2})\s+")


def extract_log_lines(path: Path):
    if not path.is_file():
        return []
    lines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = LOG_LINE_RE.match(line)
        if m:
            lines.append((m.group("ts"), line))
    return lines


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--upstream", required=True, type=Path)
    ap.add_argument("--overlay", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    args = ap.parse_args()

    entries = extract_log_lines(args.upstream) + extract_log_lines(args.overlay)
    entries.sort(key=lambda p: p[0])

    out_lines = [
        "# Operation Log",
        "",
        "*Auto-generated by `scripts/merge_log.py`. Append new entries to"
        " `overlay-log.md` in the overlay repo.*",
        "",
        "```",
    ]
    out_lines.extend(line for _, line in entries)
    out_lines.append("```")
    out_lines.append("")
    args.output.write_text("\n".join(out_lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
